### ISSUE TITLE
@ERROR: max connections (30) reached -- try again later

### ISSUE THREAD

**Issue by hc6pe** [AlmaLinux/mirrors#72]
while trying to sync almalinux we are getting:
@ERROR: max connections (30) reached -- try again later
rsync error: error starting client-server protocol (code 5) at main.c(1657) [Receiver=3.1.3]

**Comment by andrewlukoshko** [comment]
Hello.
We've experienced huge load on our mirror infrastructure last 2 days during mirroring AlmaLinux OS stable release. It's OK now.
Sorry for that.

**Comment by hohl** [comment]
@andrewlukoshko

It seems the primary repo is again somewhat overloaded. [mirror.alwyzon.net/almalinux](http://mirror.alwyzon.net/almalinux) is now slightly outdated because all the most recent cronjobs failed with:

```
@ERROR: max connections (30) reached -- try again later
rsync error: error starting client-server protocol (code 5) at main.c(1675) [Receiver=3.1.3]
```

Already tried to shift the cronjob to another time offset—hoping to find an unused window—but that didn't help either.
