### ISSUE TITLE
mirrors.isu.net.sa not listed on mirrors.almalinux.org

### ISSUE THREAD

**Issue by sysdev-isu** [AlmaLinux/mirrors#748]
Dears,

We had a power issue in the past 2 months and we fixed the issue.

we updated our mirror and enabled the rsync and the mirror is synced but it is not listed in mirrors.almalinux.org

Regards
Sam

**Comment by soksanichenko** [comment]
Hello.
It's absent in the mirrors list because the service waits that field `name` in a mirror's config is domain name (according to [wiki page](https://wiki.almalinux.org/Mirrors.html)). And the service tries to get IP of a domain. But it couldn't in that case.
I fixed the name of your mirror in the config. The mirror should appear in the mirrors list during an hour.
Thank you!

**Comment by soksanichenko** [comment]
The mirror is in the list.
![image](https://user-images.githubusercontent.com/50624082/222412141-0018a044-e9f1-48ae-86f0-e7c38e248e78.png)
